name = "cloudexpresssolution"
compatibility_date = "2025-05-11"
main = "./dist/index.html"  # Point to the entry file in the dist directory

[site]
bucket = "./dist"

[build]
command = "npm run build"